#!/bin/bash
# Recursively find all .gif files in the current directory and all its sub-directories
find . -type f -iname "*.gif" | while read file; do
    # Get the file name without its extension
    name=$(echo "$file" | sed 's/\.[^.]*$//')
    # Output the name of the file sorted by byte values, but case-insensitive
    echo "$name"
done | LC_ALL=C sort --ignore-case
# Output a newline to end the listing
echo
