#!/bin/bash

PIDFILE=/var/run/my_process.pid

start() {
    if [ -f $PIDFILE ]; then
        echo "manage_my_process is already running. PID: $(cat $PIDFILE)"
    else
        nohup ./manage_my_process >/dev/null 2>&1 &
        echo $! > $PIDFILE
        echo "manage_my_process started."
    fi
}

stop() {
    if [ -f $PIDFILE ]; then
        kill $(cat $PIDFILE)
        rm $PIDFILE
        echo "manage_my_process stopped."
    else
        echo "manage_my_process is not running."
    fi
}

restart() {
    stop
    start
    echo "manage_my_process restarted."
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    restart)
        restart
        ;;
    *)
        echo "Usage: $0 {start|stop|restart}"
        exit 1
esac

exit 0
